# Generated by Django 4.2 on 2023-09-20 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=256, verbose_name='Название')),
                ('link', models.URLField(blank=True, null=True, unique=True, verbose_name='Ссылка на урок')),
                ('duration', models.IntegerField(default=0, verbose_name='Длительность урока ')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='LessonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Уроки',
                'verbose_name_plural': 'Уроки в составе продукта',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(db_index=True, max_length=256, verbose_name='Название')),
                ('lessons', models.ManyToManyField(through='products.LessonProduct', to='products.lesson', verbose_name='Продукты')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Продукт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты пользователя',
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=15, verbose_name=' Статус')),
                ('time', models.IntegerField(blank=True, verbose_name='Время просмотра')),
                ('date', models.DateField(blank=True, verbose_name='Дата просмотра')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уроки',
                'verbose_name_plural': 'Уроки пользователя',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(through='products.UserProduct', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AddField(
            model_name='lessonproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_product', to='products.product', verbose_name='Продукт'),
        ),
        migrations.AddConstraint(
            model_name='userproduct',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product'),
        ),
        migrations.AddConstraint(
            model_name='userlesson',
            constraint=models.UniqueConstraint(fields=('user', 'lesson'), name='unique_user_lesson'),
        ),
        migrations.AddConstraint(
            model_name='lessonproduct',
            constraint=models.UniqueConstraint(fields=('lesson', 'product'), name='unique_lesson_product'),
        ),
    ]
