# Generated by Django 4.2 on 2023-09-22 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_rename_date_userlesson_date_viewing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonproduct',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_product', to='products.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='date_viewing',
            field=models.DateField(blank=True, null=True, verbose_name='Дата просмотра'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_user', to='products.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='viewing_duration',
            field=models.IntegerField(default=0, verbose_name='Время просмотра'),
        ),
    ]
