# Generated by Django 4.2 on 2023-09-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_lessonproduct_lesson_alter_product_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='userlesson',
            old_name='date_viewing',
            new_name='view_date',
        ),
        migrations.RenameField(
            model_name='userlesson',
            old_name='viewing_duration',
            new_name='view_duration',
        ),
    ]
