# Generated by Django 4.2 on 2023-09-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_user_product_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lessons',
            field=models.ManyToManyField(through='products.LessonProduct', to='products.lesson', verbose_name='Уроки'),
        ),
        migrations.AlterField(
            model_name='userlesson',
            name='status',
            field=models.BooleanField(verbose_name=' Статус'),
        ),
    ]
